### ISSUE TITLE
Issue importing GDAX data

### ISSUE THREAD

**Issue by flamewheel** [TulipCharts/tulipnode#20]
I've gotten the bot and all dependencies installed, and I was looking to do some backtesting on GDAX USD-ETH. After going to the importer and choosing GDAX, USD, ETH for Exchange/Currency/Asset (left date range as default), almost immediately after the API call initialized, the child process was killed.

Looks like the call isn't working properly, since there's no data. `_.last(data)` returns nothing so overall var process fails to be populated. Error in question is occurring on line 242 of ...\gekko-stable\exchanges\gdax.js

```
TypeError: Cannot read property 'time' of undefined
    at Trader.<anonymous> (C:\Users\George Zhao\Desktop\gekko-stable\exchanges\gdax.js:248:37)
    at Request._callback (C:\Users\George Zhao\Desktop\gekko-stable\node_modules\gdax\lib\clients\public.js:45:7)
    at Request.self.callback (C:\Users\George Zhao\Desktop\gekko-stable\node_modules\gdax\node_modules\request\request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\George Zhao\Desktop\gekko-stable\node_modules\gdax\node_modules\request\request.js:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\George Zhao\Desktop\gekko-stable\node_modules\gdax\node_modules\request\request.js:965:12)
    at emitNone (events.js:111:20)
RECEIVED ERROR IN IMPORT 521069103446476
```

**Comment by flamewheel** [comment]
Sorry - posted to the wrong repo :)
