### ISSUE TITLE
Can't install with yarn

### ISSUE THREAD

**Issue by cyberwombat** [TulipCharts/tulipnode#21]
Using Yarn the install fails with:

     Couldn't find a package.json file in "/.../node_modules/tulind/node_modules/node-pre-gyp"

Works with npm. Might be `node-pre-gyp` related from what I could google for other packages having similar issues.

**Comment by saulfautley** [comment]
Not sure if this is related, but I get the following from yarn every time I use it...

```
warning "tulind@0.8.9" is missing a bundled dependency "node-pre-gyp". This should be reported to the package maintainer.
```

**Comment by remcorakers** [comment]
I just experienced the same issue, but after upgrading yarn to the latest version (currently v1.5.1) the issue disappeared. I now can install `tulind` again with yarn without issues.

**Comment by lropero** [comment]
Yarn 1.13.0 is failing again. (Node 9.11.2)

`warning "tulind@0.8.13" is missing a bundled dependency "node-pre-gyp". This should be reported to the package maintainer.`

```
error /node_modules/tulind: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /node_modules/tulind
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@9.11.2 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/node_modules/tulind/lib/binding/Release/node-v59-darwin-x64/tulind.node" (not found)
node-pre-gyp http GET https://tulipnode.s3.amazonaws.com/tulind/v0.8.13/Release/tulind-v0.8.13-node-v59-darwin-x64.tar.gz
node-pre-gyp http 404 https://tulipnode.s3.amazonaws.com/tulind/v0.8.13/Release/tulind-v0.8.13-node-v59-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.13/Release/tulind-v0.8.13-node-v59-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for tulind@0.8.13 and node@9.11.2 (node-v59 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://tulipnode.s3.amazonaws.com/tulind/v0.8.13/Release/tulind-v0.8.13-node-v59-darwin-x64.tar.gz 
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:936:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/node_modules/tulind/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /node_modules/tulind
node-pre-gyp ERR! node -v v9.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp clean' (1)
```
