### ISSUE TITLE
Installation fails - troubleshooting ideas?

### ISSUE THREAD

**Issue by tiagosiebler** [TulipCharts/tulipnode#40]
Hello, any idea what might be causing this installation to fail? I think this file is causing the error, but it seems to be a delta file generated during installation, so it doesn't make sense to me...

This is generally working, unless it's run within this CI execution (abstruse, similar to travis).

```
sed: can't read ./Release/.deps/Release/obj.target/tulind/tulind.o.d.raw: No such file or directory
rm: cannot remove './Release/.deps/Release/obj.target/tulind/tulind.o.d.raw': No such file or directory
tulind.target.mk:105: recipe for target 'Release/obj.target/tulind/tulind.o' failed
make: *** [Release/obj.target/tulind/tulind.o] Error 1
make: Leaving directory '/home/abstruse/build/node_modules/tulind/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
```

# Full trace:
```

> tulind@0.8.12 install /home/abstruse/build/node_modules/tulind
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.12/Release/tulind-v0.8.12-node-v64-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for tulind@0.8.12 and node@10.10.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Pre-built binaries not installable for tulind@0.8.12 and node@10.10.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file 
make: Entering directory '/home/abstruse/build/node_modules/tulind/build'
CXX(target) Release/obj.target/tulind/tulind.o
make: Entering directory '/home/abstruse/build/node_modules/tulind/build'
CXX(target) Release/obj.target/tulind/tulind.o
../tulind.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE startbyindex(Nan::NAN_METHOD_ARGS_TYPE)':
../tulind.cpp:72:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (ind->options != options->Length()) {
~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../tulind.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE callbyindex(Nan::NAN_METHOD_ARGS_TYPE)':
../tulind.cpp:127:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (ind->inputs != inputs->Length()) {
~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
../tulind.cpp:134:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (ind->options != options->Length()) {
~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../tulind.cpp:236:85: warning: 'v8::Local Nan::MakeCallback(v8::Local, v8::Local, int, v8::Local*)' is deprecated [-Wdeprecated-declarations]
Nan::MakeCallback(Nan::GetCurrentContext()->Global(), callbackHandle, 2, cb_argv);
^
In file included from ../tulind.cpp:25:0:
../../nan/nan.h:958:46: note: declared here
NAN_DEPRECATED inline v8::Local MakeCallback(
^~~~~~~~~~~~
../tulind.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE startbyindex(Nan::NAN_METHOD_ARGS_TYPE)':
../tulind.cpp:72:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (ind->options != options->Length()) {
~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../tulind.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE callbyindex(Nan::NAN_METHOD_ARGS_TYPE)':
../tulind.cpp:127:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (ind->inputs != inputs->Length()) {
~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
../tulind.cpp:134:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (ind->options != options->Length()) {
~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../tulind.cpp:236:85: warning: 'v8::Local Nan::MakeCallback(v8::Local, v8::Local, int, v8::Local*)' is deprecated [-Wdeprecated-declarations]
Nan::MakeCallback(Nan::GetCurrentContext()->Global(), callbackHandle, 2, cb_argv);
^
In file included from ../tulind.cpp:25:0:
../../nan/nan.h:958:46: note: declared here
NAN_DEPRECATED inline v8::Local MakeCallback(
^~~~~~~~~~~~
CC(target) Release/obj.target/tulind/external/tiamalgamation.o
sed: can't read ./Release/.deps/Release/obj.target/tulind/tulind.o.d.raw: No such file or directory
rm: cannot remove './Release/.deps/Release/obj.target/tulind/tulind.o.d.raw': No such file or directory
tulind.target.mk:105: recipe for target 'Release/obj.target/tulind/tulind.o' failed
make: *** [Release/obj.target/tulind/tulind.o] Error 1
make: Leaving directory '/home/abstruse/build/node_modules/tulind/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/home/abstruse/.nvm/versions/node/v10.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack at ChildProcess.emit (events.js:182:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.15.0-35-generic
gyp ERR! command "/home/abstruse/.nvm/versions/node/v10.10.0/bin/node" "/home/abstruse/.nvm/versions/node/v10.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/abstruse/build/node_modules/tulind/lib/binding/Release/node-v64-linux-x64/tulind.node" "--module_name=tulind" "--module_path=/home/abstruse/build/node_modules/tulind/lib/binding/Release/node-v64-linux-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/abstruse/build/node_modules/tulind
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/abstruse/.nvm/versions/node/v10.10.0/bin/node /home/abstruse/.nvm/versions/node/v10.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/abstruse/build/node_modules/tulind/lib/binding/Release/node-v64-linux-x64/tulind.node --module_name=tulind --module_path=/home/abstruse/build/node_modules/tulind/lib/binding/Release/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack at ChildProcess. (/home/abstruse/build/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.15.0-35-generic
node-pre-gyp ERR! command "/home/abstruse/.nvm/versions/node/v10.10.0/bin/node" "/home/abstruse/build/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/abstruse/build/node_modules/tulind
node-pre-gyp ERR! node -v v10.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/home/abstruse/.nvm/versions/node/v10.10.0/bin/node /home/abstruse/.nvm/versions/node/v10.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/abstruse/build/node_modules/tulind/lib/binding/Release/node-v64-linux-x64/tulind.node --module_name=tulind --module_path=/home/abstruse/build/node_modules/tulind/lib/binding/Release/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tulind@0.8.12 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tulind@0.8.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/abstruse/.npm/_logs/2018-09-19T15_56_04_021Z-debug.log

[error]: executed command returned exit code 1
```

**Comment by tiagosiebler** [comment]
So not sure if `--fallback-to-build` is working as intended... 

I tweaked my CI build rule to use `npm install --build-from-source` instead of `npm install` during the test process, and this seems to work successfully now. I'll leave it up to you if you want to close this, at least it's documented for anyone else fighting the same thing.

**Comment by tiagosiebler** [comment]
Really quirky, even interrupting it and manually running npm install in the same env works fine...

I'll just close this for now, hopefully `--build-from-source` helps anyone else fighting this or I guess they can reopen it.
