### ISSUE TITLE
Node 10 support

### ISSUE THREAD

**Issue by Tomatipasta** [TulipCharts/tulipnode#42]
After upgrading to node 10.12.0 tulind compilations started to fail. (Both OSX and Debian based build servers)

```
warning: comparison of integers of different signs: 'const int' and    if (ind->options != options->Length()) {
'uint32_t' (aka 'unsigned int')        ~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~
[-Wsign-compare]
    if (ind->options != options->Length()) {
        ~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~
10 warnings generated.
10 warnings generated.
rm: ./Release/.deps/Release/obj.target/tulind/tulind.o.d.raw: No such file or directory
make: *** [Release/obj.target/tulind/tulind.o] Error 1
gyp  CC(target) Release/obj.target/tulind/external/tiamalgamation.o
 ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/Cellar/node/10.12.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/<username>/Desktop/bytebot/bytebot-indicators-technical/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64/tulind.node" "--module_name=tulind" "--module_path=/Users/<username>/Desktop/bytebot/bytebot-indicators-technical/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/<username>/Desktop/bytebot/bytebot-indicators-technical/node_modules/tulind
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.12.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/<username>/Desktop/bytebot/bytebot-indicators-technical/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64/tulind.node --module_name=tulind --module_path=/Users/<username>/Desktop/bytebot/bytebot-indicators-technical/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/<username>/Desktop/bytebot/bytebot-indicators-technical/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.0.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.12.0/bin/node" "/Users/<username>/Desktop/bytebot/bytebot-indicators-technical/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/<username>/Desktop/bytebot/bytebot-indicators-technical/node_modules/tulind
node-pre-gyp ERR! node -v v10.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
```

Any known solutions?

**Comment by ManuCart** [comment]
Not tested with v.10.12 but `with v10.10 it's working
``
> tulind@0.8.13 install /home/dev/competition/node_modules/tulind
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.13/Release/tulind-v0.8.13-node-v64-linux-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for tulind@0.8.13 and node@10.10.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory '/home/dev/competition/node_modules/tulind/build'
  CXX(target) Release/obj.target/tulind/tulind.o
../tulind.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE startbyindex(Nan::NAN_METHOD_ARGS_TYPE)’:
../tulind.cpp:72:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->options != options->Length()) {
         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../tulind.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE callbyindex(Nan::NAN_METHOD_ARGS_TYPE)’:
../tulind.cpp:127:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->inputs != inputs->Length()) {
         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
../tulind.cpp:134:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->options != options->Length()) {
         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../tulind.cpp:236:85: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), callbackHandle, 2, cb_argv);
                                                                                     ^
In file included from ../tulind.cpp:25:0:
../../nan/nan.h:958:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  CC(target) Release/obj.target/tulind/external/tiamalgamation.o
  SOLINK_MODULE(target) /home/dev/competition/node_modules/tulind/lib/binding/Release/node-v64-linux-arm/tulind.node
  COPY Release/tulind.node
make: Leaving directory '/home/dev/competition/node_modules/tulind/build'
``

**Comment by Tomatipasta** [comment]
Doing `npm install` (tulind 0.8.13 as dependency in package.json) - NOT OK
Doing `npm install tulind `--build-from-source manually in commandline - OK
Doing `npm install tulind` - NOT OK

**Comment by Tomatipasta** [comment]
``

**Comment by codeplea** [comment]
I should look into this when I have time.

I also need to add pre-built node v10 binaries for the Windows users.

**Comment by codeplea** [comment]
I'm hopeful that the newest version (0.8.14) fixes these issues. Binaries are now published for v10 and v11. I'm closing this, but please open a new issue if the problems persist.
