### ISSUE TITLE
installation with npm failed

### ISSUE THREAD

**Issue by ynzheng** [TulipCharts/tulipnode#43]
yn@hostdoc:~/github.com/askmike/gekko$ npm install tulind

> tulind@0.8.13 install /home/yn/github.com/askmike/gekko/node_modules/tulind
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.13/Release/tulind-v0.8.13-node-v64-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for tulind@0.8.13 and node@10.11.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for tulind@0.8.13 and node@10.11.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
make: Entering directory '/home/yn/github.com/askmike/gekko/node_modules/tulind/build'
make: Entering directory '/home/yn/github.com/askmike/gekko/node_modules/tulind/build'
  CXX(target) Release/obj.target/tulind/tulind.o
  CXX(target) Release/obj.target/tulind/tulind.o
../tulind.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE startbyindex(Nan::NAN_METHOD_ARGS_TYPE)’:
../tulind.cpp:72:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->options != options->Length()) {
         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../tulind.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE callbyindex(Nan::NAN_METHOD_ARGS_TYPE)’:
../tulind.cpp:127:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->inputs != inputs->Length()) {
         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
../tulind.cpp:134:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->options != options->Length()) {
         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../tulind.cpp:236:85: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), callbackHandle, 2, cb_argv);
                                                                                     ^
In file included from ../tulind.cpp:25:0:
../../nan/nan.h:929:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../tulind.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE startbyindex(Nan::NAN_METHOD_ARGS_TYPE)’:
../tulind.cpp:72:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->options != options->Length()) {
         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../tulind.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE callbyindex(Nan::NAN_METHOD_ARGS_TYPE)’:
../tulind.cpp:127:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->inputs != inputs->Length()) {
         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
../tulind.cpp:134:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->options != options->Length()) {
         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../tulind.cpp:236:85: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), callbackHandle, 2, cb_argv);
                                                                                     ^
In file included from ../tulind.cpp:25:0:
../../nan/nan.h:929:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
rm: cannot remove './Release/.deps/Release/obj.target/tulind/tulind.o.d.raw': No such file or directory
tulind.target.mk:105: recipe for target 'Release/obj.target/tulind/tulind.o' failed
make: *** [Release/obj.target/tulind/tulind.o] Error 1
make: Leaving directory '/home/yn/github.com/askmike/gekko/node_modules/tulind/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/yn/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/home/yn/.nvm/versions/node/v10.11.0/bin/node" "/home/yn/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/yn/github.com/askmike/gekko/node_modules/tulind/lib/binding/Release/node-v64-linux-x64/tulind.node" "--module_name=tulind" "--module_path=/home/yn/github.com/askmike/gekko/node_modules/tulind/lib/binding/Release/node-v64-linux-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/yn/github.com/askmike/gekko/node_modules/tulind
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/yn/.nvm/versions/node/v10.11.0/bin/node /home/yn/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/yn/github.com/askmike/gekko/node_modules/tulind/lib/binding/Release/node-v64-linux-x64/tulind.node --module_name=tulind --module_path=/home/yn/github.com/askmike/gekko/node_modules/tulind/lib/binding/Release/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/yn/github.com/askmike/gekko/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.9.0-8-amd64
node-pre-gyp ERR! command "/home/yn/.nvm/versions/node/v10.11.0/bin/node" "/home/yn/github.com/askmike/gekko/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/yn/github.com/askmike/gekko/node_modules/tulind
node-pre-gyp ERR! node -v v10.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/home/yn/.nvm/versions/node/v10.11.0/bin/node /home/yn/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/yn/github.com/askmike/gekko/node_modules/tulind/lib/binding/Release/node-v64-linux-x64/tulind.node --module_name=tulind --module_path=/home/yn/github.com/askmike/gekko/node_modules/tulind/lib/binding/Release/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi' (1)
  CC(target) Release/obj.target/tulind/external/tiamalgamation.o
sh: 0: getcwd() failed: No such file or directory
mkdir: cannot create directory ‘Release’: No such file or directory
mkdir: cannot create directory ‘./Release’: No such file or directory
tulind.target.mk:102: recipe for target 'Release/obj.target/tulind/external/tiamalgamation.o' failed
make: *** [Release/obj.target/tulind/external/tiamalgamation.o] Error 1
make: Leaving directory '/home/yn/github.com/askmike/gekko/node_modules/tulind/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/yn/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/home/yn/.nvm/versions/node/v10.11.0/bin/node" "/home/yn/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/yn/github.com/askmike/gekko/node_modules/tulind/lib/binding/Release/node-v64-linux-x64/tulind.node" "--module_name=tulind" "--module_path=/home/yn/github.com/askmike/gekko/node_modules/tulind/lib/binding/Release/node-v64-linux-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/yn/github.com/askmike/gekko/node_modules/tulind
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tulind@0.8.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tulind@0.8.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yn/.npm/_logs/2018-10-23T13_58_52_054Z-debug.log

**Comment by ynzheng** [comment]
dont know why but "npm install tulind --build-from-source" works 

clsoded
