### ISSUE TITLE
Installation with npm failed - OSX

### ISSUE THREAD

**Issue by bengrunfeld** [TulipCharts/tulipnode#46]
As per #43 I tried with `--build-from-source` but that also did not work. 

**System:**
MacOS Sierra: 10.12.6
Node: v10.0.0
Npm: 6.4.1

```
$ npm install --save tulind

> tulind@0.8.13 install /Users/ben/Desktop/Work/code/tradey/node_modules/tulind
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.13/Release/tulind-v0.8.13-node-v64-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for tulind@0.8.13 and node@10.0.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/local/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:947:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:368:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:598:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/ben/.nvm/versions/node/v10.0.0/bin/node" "/Users/ben/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/ben/Desktop/Work/code/tradey/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64/tulind.node" "--module_name=tulind" "--module_path=/Users/ben/Desktop/Work/code/tradey/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/ben/Desktop/Work/code/tradey/node_modules/tulind
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/ben/.nvm/versions/node/v10.0.0/bin/node /Users/ben/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/ben/Desktop/Work/code/tradey/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64/tulind.node --module_name=tulind --module_path=/Users/ben/Desktop/Work/code/tradey/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ben/Desktop/Work/code/tradey/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:947:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/Users/ben/.nvm/versions/node/v10.0.0/bin/node" "/Users/ben/Desktop/Work/code/tradey/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ben/Desktop/Work/code/tradey/node_modules/tulind
node-pre-gyp ERR! node -v v10.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/Users/ben/.nvm/versions/node/v10.0.0/bin/node /Users/ben/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/ben/Desktop/Work/code/tradey/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64/tulind.node --module_name=tulind --module_path=/Users/ben/Desktop/Work/code/tradey/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tulind@0.8.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tulind@0.8.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ben/.npm/_logs/2018-12-03T02_03_17_054Z-debug.log
```

**Comment by bengrunfeld** [comment]
Solved the issue. Brew was out of date. Just run the following:

```
brew update
brew doctor
```

**Comment by codeplea** [comment]
I'm glad it's working! Thanks for posting the solution. I haven't tested with node 10 at all yet.

**Comment by cxsper** [comment]
@bengrunfeld I don't really know how did you managed to fix this with `brew update` because this `import sys; print "%s.%s.%s" % sys.version_info[:3];` is python2 whereas, in my belief, you have had python3 under `/usr/bin/python`. Python3 throws syntaxerror when executing `print 'abc'` whereas executing the same code with python2 is ok. So apparently python3 forces to use parentheses.

So had I. I've had python3 on my machine with symbolic link under `/usr/bin/python`. And for python3 `print 'abc'` is illegal statement which causes syntax error.

So I installed python2, replaced symbolic link under `/usr/bin/python` to python2, made `npm i tulind --build-from-source` and it works.

No updates have been required and I am really curious how did you managed to fix it with your `brew`.

Anyway, @codeplea I can confirm that `tulind` works with:
node v11.4.0
npm v6.5.0
python v2.7.15 under `/usr/bin/python`
node-gyp v3.8.0

**Comment by bengrunfeld** [comment]
@cxsper to be honest, I don't really know myself. I had read about that fix from someone else's issue (can't remember where) so I gave it a shot myself and it worked. There were no other steps that I took to fix the error. Sorry I can't be of more help.

**Comment by Negar-Ebrahimi** [comment]
@cxsper I ran brew update and nothing happened because I already had my brew updated! Just as you pointed out the issue about Python's version incompatibility, I had both Python 2 and Python 3 installed and version 3 was under /usr/bin/python. What happened by running brew doctor was that it required me to unlink python@2 and link it again. Then, -I guess- python3 was replaced by python2 in the very directory and the syntax error was gone.

**Comment by dmitriz** [comment]
The error has nothing to do with `brew`, it tries to download non-existent file:

```sh
node-pre-gyp WARN Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.13/Release/tulind-v0.8.13-node-v64-darwin-x64.tar.gz
```

I can only guess the location has been moved elsewhere while this lib still keeps trying the old one. A simple fix would be to update the new location, so if anyone knows it, please share.

**Comment by codeplea** [comment]
@dmitriz No, pre-built binaries for darwin don't exist. It falls back to building from source, which is normal.

**Comment by dmitriz** [comment]
@codeplea If building is indeed expected on every single installation, it is a bad news for me (and everyone in the same situation, possibly also the OP), as my build system seems also to fail:

```sh
→ npm install tulind

> tulind@0.8.15 install /Users/dmitrizaitsev/test/tulip/node_modules/tulind
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.15/Release/tulind-v0.8.15-node-v64-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for tulind@0.8.15 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  CXX(target) Release/obj.target/tulind/tulind.o
error: invalid value 'gnu++1y' in '-std=gnu++1y'
make: *** [Release/obj.target/tulind/tulind.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 12.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/dmitrizaitsev/test/tulip/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64/tulind.node" "--module_name=tulind" "--module_path=/Users/dmitrizaitsev/test/tulip/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /Users/dmitrizaitsev/test/tulip/node_modules/tulind
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/dmitrizaitsev/test/tulip/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64/tulind.node --module_name=tulind --module_path=/Users/dmitrizaitsev/test/tulip/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/dmitrizaitsev/test/tulip/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 12.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/dmitrizaitsev/test/tulip/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/dmitrizaitsev/test/tulip/node_modules/tulind
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/dmitrizaitsev/test/tulip/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64/tulind.node --module_name=tulind --module_path=/Users/dmitrizaitsev/test/tulip/node_modules/tulind/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tulind@0.8.15 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tulind@0.8.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dmitrizaitsev/.npm/_logs/2019-07-15T07_59_58_240Z-debug.log
```

Having pre-built binaries instead also for darwin would save this pain, but I also appreciate any help diagnosing that build problem.

**Comment by soltanianmj** [comment]
on mac os install xcode command line tools it will fix the problem but i have a script and i want to run it on windows server 2012 and actually i have no idea what to do.i try installing node-gyp node-pre-gyp and node-pre-gyp install --fallback-to-build and c++ build environment but again failed even i try to copy node module from mac os to windows server but failed again.
