### ISSUE TITLE
I can not install tulind in CentOS 6.9, please help me

### ISSUE THREAD

**Issue by viniciussvl** [TulipCharts/tulipnode#52]
I am trying to install the node tulind package on my linux server in CentOS 6.9 production, however I am not getting it, I installed everything that was needed, python2.7, groupinstall development tools and even node-gyp and node-pre-gyp globally with npm and I can not resolve this error.

On windows it works normally, because I installed windows-build-tools on my computer, now on the server in production I can not make it work in CentOS, can anyone help me please?

See the huge message I get when running npm install:

`node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.15/Release/tulind-v0.8.15-node-v64-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for tulind@0.8.15 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory `/home/vinicius/alvs.vinicius.net/node_modules/tulind/build'
  CXX(target) Release/obj.target/tulind/tulind.o
cc1plus: error: unrecognized command line option "-std=gnu++1y"
make: *** [Release/obj.target/tulind/tulind.o] Error 1
make: Leaving directory `/home/vinicius/alvs.vinicius.net/node_modules/tulind/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.9.78-xxxx-std-ipv6-64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/vinicius/alvs.vinicius.net/node_modules/tulind/lib/binding/Release/node-v64-linux-x64/tulind.node" "--module_name=tulind" "--module_path=/home/vinicius/alvs.vinicius.net/node_modules/tulind/lib/binding/Release/node-v64-linux-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /home/vinicius/alvs.vinicius.net/node_modules/tulind
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/vinicius/alvs.vinicius.net/node_modules/tulind/lib/binding/Release/node-v64-linux-x64/tulind.node --module_name=tulind --module_path=/home/vinicius/alvs.vinicius.net/node_modules/tulind/lib/binding/Release/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/vinicius/alvs.vinicius.net/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.9.78-xxxx-std-ipv6-64
node-pre-gyp ERR! command "/usr/bin/node" "/home/vinicius/alvs.vinicius.net/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/vinicius/alvs.vinicius.net/node_modules/tulind
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/vinicius/alvs.vinicius.net/node_modules/tulind/lib/binding/Release/node-v64-linux-x64/tulind.node --module_name=tulind --module_path=/home/vinicius/alvs.vinicius.net/node_modules/tulind/lib/binding/Release/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tulind@0.8.15 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tulind@0.8.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-03T18_11_44_821Z-debug.log`

**Comment by codeplea** [comment]
What output do you get if you run `g++ --version`?

**Comment by viniciussvl** [comment]
Thank you for your response!

g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO

________________________________
De: Lewis Van Winkle <notifications@github.com>
Enviado: Wednesday, April 3, 2019 4:21:56 PM
Para: TulipCharts/tulipnode
Cc: Vinicius Aquino; Author
Assunto: Re: [TulipCharts/tulipnode] I can not install tulind in CentOS 6.9, please help me (#52)


What output do you get if you run g++ --version?
