### ISSUE TITLE
TypeError: Expecting third argument to be array of options.

### ISSUE THREAD

**Issue by thegamecat** [TulipCharts/tulipnode#6]
tulind.indicators.sma.indicator(this.candleProps.close,[14], function(err, results) {
			console.log("Result of sma is:");
			console.log(results[0]);
		});

return tulind.callbyindex(index, inputs, options, callback);
                  ^

TypeError: Expecting third argument to be array of options.
    at Object.indicator (/mnt/f/bash/gekko/node_modules/tulind/index.js:10:19)
    at Base.method.update (/mnt/f/bash/gekko/strategies/test.js:218:25)
    at Base.bound [as update] (/mnt/f/bash/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.propogateTick (/mnt/f/bash/gekko/plugins/tradingAdvisor/baseTradingMethod.js:220:8)
    at Base.bound [as propogateTick] (/mnt/f/bash/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.tick (/mnt/f/bash/gekko/plugins/tradingAdvisor/baseTradingMethod.js:171:10)
    at Base.bound [as tick] (/mnt/f/bash/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Actor.processCustomCandle (/mnt/f/bash/gekko/plugins/tradingAdvisor/tradingAdvisor.js:75:15)
    at CandleBatcher.bound (/mnt/f/bash/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at emitOne (events.js:96:13)
    at CandleBatcher.emit (events.js:189:7)

**Comment by codeplea** [comment]
What is `this.candleProps.close`? Did you try `[this.candleProps.close]`?

**Comment by codeplea** [comment]
Based on the error message, I'm not sure the code that you posted is actually what you ran. You should provided a minimal, but complete, example.

**Comment by thegamecat** [comment]
> What is this.candleProps.close? Did you try [this.candleProps.close]?

It's probably that, I'll test it.
