### ISSUE TITLE
tulind@0.8.18 can't be installed

### ISSUE THREAD

**Issue by lafafm** [TulipCharts/tulipnode#85]
Today got an issue with a tulind@0.8.18, as it seems no longer to be on aws (version 0.8.20 still available btw)

```
> tulind@0.8.18 install 
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.18/Release/tulind-v0.8.18-node-v83-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for tulind@0.8.18 and node@14.21.2 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 500 status code downloading checksum
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:273:18)
gyp ERR! stack     at Request.emit (events.js:412:35)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1066:10)
gyp ERR! stack     at ClientRequest.emit (events.js:400:28)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:515:22)
gyp ERR! stack     at TLSSocket.emit (events.js:400:28)
gyp ERR! stack     at addChunk (internal/streams/readable.js:293:12)
gyp ERR! stack     at readableAddChunk (internal/streams/readable.js:267:9)
```

**Comment by lafafm** [comment]
Seems to be a network issue, and prebuild for 0.8.18 was missing for a long time
